name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4.10.0, 4.9.0]
        dist: ["alpine", "debian", "fedora", "ubuntu"]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: make build CV=${{ matrix.version }} DIST=${{ matrix.dist }}
      - name: Test
        run: make test CV=${{ matrix.version }} DIST=${{ matrix.dist }}
      - name: Push
        run: make push CV=${{ matrix.version }} DIST=${{ matrix.dist }}
  latest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Latest
        run: make latest CV=4.10.0 DIST=fedora
